version: "3.8"
services:
  polardb-catalog:
    image: "postgres:13"
    container_name: "polardb-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_catalog
  polardb-order:
    image: "postgres:13"
    container_name: "polardb-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order
  catalog-service:
    image: "polarbookshop/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polardb-catalog:5432/polardb_catalog
  polardb-redis:
    image: "redis:6"
    container_name: "polardb-redis"
    ports:
      - 6379:6379
  polarmq-broker:
    image: "rabbitmq:3-management"
    container_name: "polarmq-broker"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  polar-keycloak:
    image: jboss/keycloak:14.0.0
    container_name: "polar-keycloak"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
